  /**:
    ros__parameters:
      debug: true
      target_frame: gimbal_link
      max_armor_distance: 10.0

      ekf:
        sigma2_q_x: 1.0
        sigma2_q_y: 1.0
        sigma2_q_z: 1.0

        

        r_x: 4e-3
        r_y: 4e-3
        r_z: 4e-3
        r_yaw: 1e-3

      tracker:
        max_match_distance: 0.5
        max_match_yaw_diff: 1.0
        tracking_thres: 2
        lost_time_thres: 1.0
      
      solver:
        prediction_delay: 0.08
        controller_delay: 0.0
        yaw_prediction_scale: 0.6   # 旋转预测缩放(0~1)，解耦旋转与平移的预测提前量
        min_switching_v_yaw: 2.0    # v_yaw低于此值时不启用side_angle提前切板
        max_tracking_v_yaw: 60.0 #转速(rad/s)大于这个值时瞄准机器人中心 
        side_angle: 20.0 
        bullet_speed: 23.0

        compenstator_type: "ideal"
        gravity: 9.80
        resistance: 0.08
        iteration_times: 20 # 补偿的迭代次数
        # ["距离下限, 距离上限, 高度下限, 高度下限, pitch轴补偿值 yaw"
        angle_offset: [
          "5.0 6.0 -1.0 0.4 -1.8 0.22",
          "5.0 6.0  0.4 0.8 -1.8 0.22", 
          "5.0 6.0  0.8 1.2 -1.8 0.22",
          "6.0 7.0 -1.0 0.4 -1.8 0.22",
          "6.0 7.0  0.4 0.8 -1.8 0.22",
          "6.0 7.0  0.8 1.2 -1.8 0.11",
          "7.0 8.0 -1.0 0.4 -1.8 0.11",
          "7.0 8.0  0.4 0.8 -1.8 0.11",
          "7.0 8.0  0.8 1.2 -1.8 0.11",
        ]
